### ISSUE TITLE
Practice mode?

### ISSUE THREAD

**Issue by dreamfeel** [hedalu244/diffle#2]
Hi! I absolutely looooove Diffle, I think it's the most interesting and deepest wordle-like. You should definitely consider a paid version for android/ios etc. 

That said, one thing I would absolutely die for that many wordle-clones have, is a practice mode that you can play infinitely?.Hope you don't mind the request, feel free to close if you're busy etc.

**Comment by hedalu244** [comment]
Thank you for your feedback!  I'm quite glad you enjoy the game!

Regarding the practice mode, I'm not thinking of creating it as official. Because I think, the once-per-day restriction makes the wordle-like games to be enjoyed for a long time, and playing the game several times a day may make you get tired and bored faster.

By the way, I am releasing this repository under MIT license. I welcome anyone (or you) to fork it and make an unofficial version that has the practice mode, hard mode, modified dictionary, etc.

**Comment by Deykun** [comment]
@dreamfeel I've created a React clone of diffle. Unfortunately, it's not a fork, and I can't make it a fork now. Only the compare function is from this codebase. I mention @hedalu244 's project on my page in repo. I hope he isn't mad about it. 😅

https://deykun.github.io/diffle-lang/en

My version has a practice mode.
